#!/usr/bin/env bash

echo "update dots"
  git pull origin master
  git submodule update --init --recursive

echo "symlink configs"
  ln -s ~/dotfiles/gitignore-global .gitignore-global
  ln -s ~/dotfiles/gemrc .gemrc
  ln -s ~/dotfiles/gitconfig .gitconfig
  ln -s ~/dotfiles/zshrc .zshrc
  ln -s ~/dotfiles/rbenv/default-gems ~/.rbenv/default-gems

echo 'Make zsh default shell'
chsh -s /bin/zsh

echo 'Installing brew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Updating brew..."
  brew update || true

echo "Running brew doctor..."
  brew doctor || true

echo "Installing rbenv"
  brew install rbenv

  brew install rbenv-default-gems

  brew install rbenv-gem-rehash

echo "Installing imagemagick"
  brew install imagemagick

echo "Installing redis"
  brew install redis

  ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents

  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

echo "Installing memcached"
  brew install memcached

  ln -sfv /usr/local/opt/memcached/*.plist ~/Library/LaunchAgents

  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist

echo "installing mongodb"
  brew install mongodb

  ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents

  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist

echo "Installing mysql"
  brew install mysql

  ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents

  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist

echo "Installing postgresql"
  brew install postgresql

  ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

echo "Installing node"
  brew install node

echo "Installing: pow"
  brew install pow
  mkdir -p ~/Library/Application\ Support/Pow/Hosts
  ln -sf ~/Library/Application\ Support/Pow/Hosts ~/.pow
  sudo pow --install-system
  pow --install-local
  sudo launchctl load -w /Library/LaunchDaemons/cx.pow.firewall.plist
  launchctl load -w ~/Library/LaunchAgents/cx.pow.powd.plist

echo "Installing ruby"
  rbenv install 2.1.0
  rbenv global 2.1.0

echo "Expand save panel by default"
  defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

echo "Expand print panel by default"
  defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

echo "Automatically quit printer app once the print jobs complete"
  defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

echo "Disable the “Are you sure you want to open this application?” dialog"
  defaults write com.apple.LaunchServices LSQuarantine -bool false

echo "Trackpad: enable tap to click for this user and for the login screen"
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

echo "Enable full keyboard access for all controls"
  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

echo "Use scroll gesture with the Ctrl modifier key to zoom"
  defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
  defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

echo "Follow the keyboard focus while zoomed in"
  defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

echo "Locale settings"
  defaults write NSGlobalDomain AppleLanguages -array "en" "pl"
  defaults write NSGlobalDomain AppleLocale -string "en_GB@currency=PLN"
  defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
  defaults write NSGlobalDomain AppleMetricUnits -bool true

echo "Disable shadow in screenshots"
  defaults write com.apple.screencapture disable-shadow -bool true

echo "Finder: show all filename extensions"
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true

echo "Finder: show status bar"
  defaults write com.apple.finder ShowStatusBar -bool true

echo "Finder: show path bar"
  defaults write com.apple.finder ShowPathBar -bool true

echo "Display full POSIX path as Finder window title"
  defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

echo "When performing a search, search the current folder by default"
  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

echo "Disable the warning when changing a file extension"
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

echo "Avoid creating .DS_Store files on network volumes"
  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

echo "Disable disk image verification"
  defaults write com.apple.frameworks.diskimages skip-verify -bool true
  defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
  defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

echo "Automatically open a new Finder window when a volume is mounted"
  defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
  defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
  defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

echo "Use list view in all Finder windows by default"

echo "Four-letter codes for the other view modes: icnv, clmv, Flwv"
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

echo "Disable the warning before emptying the Trash"
  defaults write com.apple.finder WarnOnEmptyTrash -bool false

echo "Empty Trash securely by default"
  defaults write com.apple.finder EmptyTrashSecurely -bool true

echo "Show the ~/Library folder"
  chflags nohidden ~/Library

echo "Minimize to app icon"
  defaults write com.apple.dock minimize-to-application -bool true

echo "Restarting Finder"
  killall Finder

echo "Put Dock on the right"
  defaults write com.apple.dock orientation -string right

echo "Autohide Dock"
  defaults write com.apple.dock autohide -boolean true

echo "Make dock transparent"
  defaults write com.apple.dock hide-mirror -bool true

echo "Restarting Dock"
  killall Dock
